baseurl: 'https://www.oregonsadventurecoast.com'
languageCode: en-us
themesDir: components
title: Oregon's Adventure Coast
googleAnalytics: UA-4406033-1
MetaDataFormat: yaml
params:
  visitorGuideLink: /visitor-guide
outputs:
  page:
    - HTML
  section:
    - HTML
    - RSS
taxonomies:
  category: categories
  tag: tags
  duration: durations
  town: towns
  tripadventure: tripadventures
permalinks:
  adventure: ':slug/'
  sitepages: ':slug/'
blackfriday:
  hrefTargetBlank: false
theme:
  - tnd-seo