[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.55.6"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"